---
##This script starts the PDB listener

- name: copy listener start script to {{ server_name }}
  copy:
    src: "{{ start_listener_script }}"
    dest: "{{ remote_script_directory }}/{{ start_listener_script }}"
    mode: "{{script_permission}}"
    force: yes
  delegate_to: "{{ server_name }}"

- name: start listener {{ ORACLE_SID }} on {{ server_name }}
  shell: >
    {{ remote_script_directory }}/{{ start_listener_script }} start
    {{ ORACLE_SID }} {{ sid_server_dict[ORACLE_SID].pdbListener }}
    &> >(tee {{ remote_output_directory }}/log.start_PDB_listener.`date +"%Y.%m.%d"`)
  args:
    executable: /usr/bin/bash
  delegate_to: "{{ server_name }}"
  register: listener_start_status
  become: yes
  become_user: "{{ sid_server_dict[ORACLE_SID].dbowner }}"
  become_method: sudo
  failed_when: listener_start_status.rc != 4 and listener_start_status.rc != 0

- name: print start_listener_script status for {{ ORACLE_SID }}
  debug:
    msg: "{{ listener_start_status.stdout_lines }}"
  failed_when: listener_start_status.rc == 4
